### ISSUE TITLE
Follower crashes with "unable to sync burnchain" on startup

### ISSUE THREAD

**Issue by diwakergupta** [blockstack/stacks-blockchain#1474]
**Describe the bug**
Follower crashes with the following config:

```toml
[node]
rpc_bind = "0.0.0.0:20443"
p2p_bind = "0.0.0.0:20444"
bootstrap_node = "048dd4f26101715853533dee005f0915375854fd5be73405f679c1917a5d4d16aaaf3c4c0d7a9c132a36b8c5fe1287f07dad8c910174d789eb24bdfb5ae26f5f27@35.245.47.179:20444"

[burnchain]
chain = "bitcoin"
mode = "neon"
peer_host = "35.245.47.179" # can become "neon.blockstack.org" as soon as PR #1464 is merged
rpc_port = 18443
peer_port = 18444

[[mstx_balance]]
address = "ST2ZRX0K27GW0SP3GJCEMHD95TQGJMKB7G9Y0X1MH"
amount = 10000000000000000

[[mstx_balance]]
address = "ST26FVX16539KKXZKJN098Q08HRX3XBAP541MFS0P"
amount = 10000000000000000

[[mstx_balance]]
address = "ST3CECAKJ4BH08JYY7W53MC81BYDT4YDA5M7S5F53"
amount = 10000000000000000

[[mstx_balance]]
address = "ST31HHVBKYCYQQJ5AQ25ZHA6W2A548ZADDQ6S16GP"
amount = 10000000000000000
```

**Environment (please complete the following information):**
 - OS: OS X
 - Rust version: 1.40.0
 - Version of the appropriate binary / software package: master branch (at d7a8361612579116b9cceba8c594a6f7a9e51c3f)

**Additional context**
Stack trace:
```
INFO [1587640002.588] [src/chainstate/stacks/index/marf.rs:732] First-ever block 0f9188f13cb7b2c71f2a335e3a4fc328bf5beb436012afc
a590b1a11466e2206
thread '<unnamed>' panicked at 'duplicate entry: (294, 1)', src/chainstate/burn/distribution.rs:85:13
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:77
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:61
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1028
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1412
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:65
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:50
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:188
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:205
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:464
  11: std::panicking::begin_panic
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/panicking.rs:400
  12: blockstack_lib::chainstate::burn::distribution::BurnSamplePoint::make_distribution
             at src/chainstate/burn/distribution.rs:85
  13: blockstack_lib::burnchains::burnchain::<impl blockstack_lib::burnchains::BurnchainStateTransition>::from_block_ops
             at src/burnchains/burnchain.rs:143
  14: blockstack_lib::burnchains::burnchain::<impl blockstack_lib::burnchains::Burnchain>::process_checked_block_ops
             at src/burnchains/burnchain.rs:586
  15: blockstack_lib::burnchains::burnchain::<impl blockstack_lib::burnchains::Burnchain>::process_block_ops
             at src/burnchains/burnchain.rs:633
  16: blockstack_lib::burnchains::burnchain::<impl blockstack_lib::burnchains::Burnchain>::process_block_txs
             at src/burnchains/burnchain.rs:696
  17: blockstack_lib::burnchains::burnchain::<impl blockstack_lib::burnchains::Burnchain>::process_block
             at src/burnchains/burnchain.rs:709
  18: blockstack_lib::burnchains::burnchain::<impl blockstack_lib::burnchains::Burnchain>::sync_with_indexer::{{closure}}
             at src/burnchains/burnchain.rs:862
```

Followed by:
```
ERROR [1587640034.502] [testnet/src/burnchains/bitcoin_regtest_controller.rs:138] Unable to sync burnchain: Error in thread chan
nel
thread 'main' panicked at 'explicit panic', testnet/src/burnchains/bitcoin_regtest_controller.rs:139:17
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:77
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:61
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1028
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1412
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:65
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:50
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:188
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:205
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:464
  11: std::panicking::begin_panic
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/panicking.rs:400
  12: stacks_testnet::burnchains::bitcoin_regtest_controller::BitcoinRegtestController::receive_blocks
             at testnet/src/burnchains/bitcoin_regtest_controller.rs:139
  13: <stacks_testnet::burnchains::bitcoin_regtest_controller::BitcoinRegtestController as stacks_testnet::burnchains::Burnchain
Controller>::start
             at testnet/src/burnchains/bitcoin_regtest_controller.rs:504
  14: stacks_testnet::run_loop::neon::RunLoop::start
             at testnet/src/run_loop/neon.rs:37
  15: stacks_testnet::main
             at testnet/src/main.rs:61
  16: std::rt::lang_start::{{closure}}
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/rt.rs:61
  17: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:48
  18: std::panicking::try::do_call
             at src/libstd/panicking.rs:287
  19: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:78
  20: std::panicking::try
             at src/libstd/panicking.rs:265
  21: std::panic::catch_unwind
             at src/libstd/panic.rs:396
  22: std::rt::lang_start_internal
             at src/libstd/rt.rs:47
  23: std::rt::lang_start
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/rt.rs:61
  24: stacks_testnet::main
```
