### ISSUE TITLE
Miner winning but blocks being rejected

### ISSUE THREAD

**Issue by dantrevino** [blockstack/stacks-blockchain#1951]
**Describe the bug**
Copying @psq's description from discord
```
psqToday at 12:59 AM
who is running the miner with btc mmLJviAqiRtNGNueMqp9y6zraQLt2kK2iT and stx STZWTSQ05K1WCBSHGY4MQ0T2SMNV48M74C2WR3E5.  This miner is using 20_000 as the burn_fee_cap, but all its blocks are getting rejected.  What version of the source are you running (you can tell by running git rev-parse HEAD).  Ideally, if you could share your log file, and storage directory (in /tmp) with me, that would be helpful to understand why that is.
By using a larger burn fee, the miner is winning more blocks, which could be considered good, but as no blocks gets included in the chain, this would be mean 0 STX reward (and this also slows down the network since it is currently doing empty blocks for 40% of the blocks)
[1:01 AM]
The full configuration file would also help (you can remove the private key, not that it matters for testnet, but that just creates good habits...)
Thanks!
```

**Steps To Reproduce**
The only thing I've changed recently is that I set the burn_fee_cap to 20000.  Assuming this caused me to win more blocks and manifested the issue that may otherwise not exist or not be noticed.

**Expected behavior**
Blocks not being rejected

**Environment (please complete the following information):**
 - OS: `uname -a
Linux ip-172-26-13-130 5.4.0-1025-aws #25-Ubuntu SMP Fri Sep 11 09:37:24 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

 - Rust version
```
$ rustup show
Default host: x86_64-unknown-linux-gnu
rustup home:  /home/ubuntu/.rustup

stable-x86_64-unknown-linux-gnu (default)
rustc 1.46.0 (04488afe3 2020-08-24)
```
git version
```
~/stacks-blockchain$ git rev-parse HEAD
2a1cf70934b962ce166457c1c6b9b0abc5443673
```

 - Version of the appropriate binary / software package
```
$ stacks-node version
stacks-node 0.1.0 => 23.0.0.0 (master:2a1cf7093, debug build, linux [x86_64])
```
**Additional context**
krypton-miner-conf.toml
```toml
[node]
rpc_bind = "0.0.0.0:20443"
p2p_bind = "0.0.0.0:20444"
bootstrap_node = "048dd4f26101715853533dee005f0915375854fd5be73405f679c1917a5d4d16aaaf3c4c0d7a9c132a36b8c5fe1287f07dad8c910174d789eb24bdfb5ae26f5f27@krypton.blockstack.org:20444"
# Enter your private key here!
seed = "... redacted ..."
miner = true

[burnchain]
chain = "bitcoin"
mode = "krypton"
peer_host = "bitcoind.krypton.blockstack.org"
rpc_port = 18443
peer_port = 18444
process_exit_at_block_height = 5130
burn_fee_cap = 20000

[[mstx_balance]]
address = "STB44HYPYAT2BB2QE513NSP81HTMYWBJP02HPGK6"
amount = 10000000000000000
[[mstx_balance]]
address = "ST11NJTTKGVT6D1HY4NJRVQWMQM7TVAR091EJ8P2Y"
amount = 10000000000000000
[[mstx_balance]]
address = "ST1HB1T8WRNBYB0Y3T7WXZS38NKKPTBR3EG9EPJKR"
amount = 10000000000000000
[[mstx_balance]]
address = "STRYYQQ9M8KAF4NS7WNZQYY59X93XEKR31JP64CP"
amount = 10000000000000000
```

Miner log and dbs attached.
[testnet-log.tar.gz](https://github.com/blockstack/stacks-blockchain/files/5339242/testnet-log.tar.gz)
