### ISSUE TITLE
Initial/seeded account balances not propagated through event stream

### ISSUE THREAD

**Issue by zone117x** [blockstack/stacks-blockchain#2056]
No transaction or stx mint events are sent to event observers for accounts that are pre-loaded with STX balance, e.g. using a `.toml` file containing:
```toml
[[mstx_balance]]
address = "STB44HYPYAT2BB2QE513NSP81HTMYWBJP02HPGK6"
amount = 10000000000000000
[[mstx_balance]]
address = "ST11NJTTKGVT6D1HY4NJRVQWMQM7TVAR091EJ8P2Y"
amount = 10000000000000000
[[mstx_balance]]
address = "ST1HB1T8WRNBYB0Y3T7WXZS38NKKPTBR3EG9EPJKR"
amount = 10000000000000000
```

This causes incorrect balance calculations in the sidecar which results in large negative STX balances for consumers, .e.g. https://sandbox.stacks.engineering/address/STB44HYPYAT2BB2QE513NSP81HTMYWBJP02HPGK6

Should these balances be simulated as STX transfer events in the genesis block, similar to the bootcode contracts? Keep in mind the v1->v2 STX balance import process which I think will result in similar behavior.
