### ISSUE TITLE
High CPU usage while running stacks-node in follower or miner modes.

### ISSUE THREAD

**Issue by LNow** [blockstack/stacks-blockchain#2245]
**Describe the bug**
stacks-node CPU usage is ramping up above 50% and sometimes reaches over 90% and stays in this range for more than few minutes.

At the same time `stacks-node` output is filled with following entry repeated over 5000x. with only difference between each occurrence epoch timestamp.
```
WARN [1609547756.380892] [src/net/p2p.rs:4283] [ThreadId(4)] Failed to instantiate unconfirmed state: ChainstateError("Invalid stacks transaction: Bad nonce: origin account STB44HYPYAT2BB2QE513NSP81HTMYWBJP02HPGK6 nonce of tx 4572adbc94f1d7243acd5d43104c96a1f75dd53314b4f0826808d3a1f545fad9 is 62 (expected 65)")
WARN [1609547756.599157] [src/chainstate/stacks/db/transactions.rs:325] [ThreadId(4)] Bad nonce: origin account STB44HYPYAT2BB2QE513NSP81HTMYWBJP02HPGK6 nonce of tx 4572adbc94f1d7243acd5d43104c96a1f75dd53314b4f0826808d3a1f545fad9 is 62 (expected 65)
```
After few minutes of such behaviour CPU usage drops below 30% and sits around this level for next few minutes, and then again jumps to the roof with similar output.

**Steps To Reproduce**
Start stacks node either in miner or follower mode. And wait few minutes.

**Expected behavior**
CPU usage should be below 30% or even lower.

**Environment (please complete the following information):**
 - OS: Fedora 33 (Kernel: 5.9.16-200.fc33.x86_64)
 - Rust version: none, I use pre-compiled binaries
 - Version of the appropriate binary / software package: v24.3.1.0-xenon

**Additional context**
```toml
[node]
rpc_bind = "0.0.0.0:20443"
p2p_bind = "0.0.0.0:20444"
bootstrap_node = "048dd4f26101715853533dee005f0915375854fd5be73405f679c1917a5d4d16aaaf3c4c0d7a9c132a36b8c5fe1287f07dad8c910174d789eb24bdfb5ae26f5f27@xenon.blockstack.org:20444"
miner = false
working_dir = "/home/lnow/Projects/blockstack/stacks/data"

[burnchain]
chain = "bitcoin"
mode = "xenon"
peer_host = "127.0.0.1"
username = "username"
password = "password"
rpc_port = 18332
peer_port = 18333

[[ustx_balance]]
address = "STB44HYPYAT2BB2QE513NSP81HTMYWBJP02HPGK6"
amount = 10000000000000000

[[ustx_balance]]
address = "ST11NJTTKGVT6D1HY4NJRVQWMQM7TVAR091EJ8P2Y"
amount = 10000000000000000

[[ustx_balance]]
address = "ST1HB1T8WRNBYB0Y3T7WXZS38NKKPTBR3EG9EPJKR"
amount = 10000000000000000

[[ustx_balance]]
address = "STRYYQQ9M8KAF4NS7WNZQYY59X93XEKR31JP64CP"
amount = 10000000000000000
```
