### ISSUE TITLE
Slow/failed syncing with testnet

### ISSUE THREAD

**Issue by wileyj** [blockstack/stacks-blockchain#2725]
Running a follower node for testnet was failing to sync stacks blocks as expected. 
Initially, the burnchain sync went through fine - but then it took roughly 48 hours of continued operation to sync a single stacks block (the only event that happened on my side was a disconnection due to laptop lid being closed for a bit - reopened the lid, service became active again and blocks started to download). 

## Steps To Reproduce
Run a testnet node with the following config.toml:
```toml
[node]
working_dir = "/root/stacks-node/data"
rpc_bind = "0.0.0.0:20443"
p2p_bind = "0.0.0.0:20444"
bootstrap_node="047435c194e9b01b3d7f7a2802d6684a3af68d05bbf4ec8f17021980d777691f1d51651f7f1d566532c804da506c117bbf79ad62eea81213ba58f8808b4d9504ad@testnet.stacks.co:20444"
wait_time_for_microblocks = 10000

[[events_observer]]
endpoint = "stacks-node-api:3700"
retry_count = 255
events_keys = ["*"]

[burnchain]
chain = "bitcoin"
mode = "xenon"
peer_host = "bitcoin.testnet.blockstack.com"
username = "blockstack"
password = "blockstacksystem"
rpc_port = 18332
peer_port = 18333

[[ustx_balance]]
address = "STB44HYPYAT2BB2QE513NSP81HTMYWBJP02HPGK6"
amount = 10000000000000000

[[ustx_balance]]
address = "ST11NJTTKGVT6D1HY4NJRVQWMQM7TVAR091EJ8P2Y"
amount = 10000000000000000

[[ustx_balance]]
address = "ST1HB1T8WRNBYB0Y3T7WXZS38NKKPTBR3EG9EPJKR"
amount = 10000000000000000

[[ustx_balance]]
address = "STRYYQQ9M8KAF4NS7WNZQYY59X93XEKR31JP64CP"
amount = 10000000000000000

[connection_options]
read_only_call_limit_write_length = 0
read_only_call_limit_read_length = 100000
read_only_call_limit_write_count = 0
read_only_call_limit_read_count = 30
read_only_call_limit_runtime = 1000000000
```

## Expected behavior
Node will sync stacks blocks in a timely manner

## Environment
 - OS: Docker (`Docker version 20.10.6, build 370c289`)
 - Image: `blockstack/stacks-blockchain:latest` (same as tagged image `2.0.11.1.0`)
   -  `sha256:c77148c2b62c19602caece38a0bfc1a7b5fe88baa082c5e3ac4439d806968ffe`

## Additional context
Logs of the the node are attached in txt format
[testnet.txt](https://github.com/blockstack/stacks-blockchain/files/6687256/testnet.txt)
