### ISSUE TITLE
Poor synchronization performance

### ISSUE THREAD

**Issue by LNow** [blockstack/stacks-blockchain#2933]
**Describe the bug**
Synchronizing full stacks-node is a very slow process. It took me over a week to do it once (with fully synchronized local BTC node).

After restart it hangs on Bitcoin blocks synchronization for 2-3h, despite the fact that it was off for no more than 5min. When that happen all I see is this: 
```
INFO [1637167883.909787] [testnet/stacks-node/src/run_loop/neon.rs:168] [main] Will run as a Follower node
INFO [1637167883.909903] [testnet/stacks-node/src/run_loop/neon.rs:175] [main] Start syncing Bitcoin headers, feel free to grab a cup of coffee, this can take a while
INFO [1637167884.509132] [src/burnchains/burnchain.rs:1265] [main] Syncing Bitcoin blocks: 100.0% (710159 to 710160 out of 710159)
```
When I try to run synchronization from scratch `Syncing Bitcoin blocks` progress starts at `4.8%`level and it is not updated until it fully synchronize all blocks.

I understand that it takes time to synchronize node, but during time required to synchronize stack-node I can setup full BTC node 3-4 times in a row.

**Expected behavior**
Synchronization should not take more than setting up full BTC node from scratch.

**Environment (please complete the following information):**
`stacks-node v2.0.11.4.0`

**Comment by jcnelson** [comment]
Hi @LNow, it would be very helpful if you provided full debug logs.  There's not much I can do with the information you've provided.

**Comment by LNow** [comment]
I'm sorry @jcnelson, I forgot to save them.

`Config.toml`
```toml
[node]
working_dir = "/home/lnow/Projects/blockstack/follower"
rpc_bind = "0.0.0.0:22443"
p2p_bind = "0.0.0.0:22444"
bootstrap_node = "02da7a464ac770ae8337a343670778b93410f2f3fef6bea98dd1c3e9224459d36b@seed-0.mainnet.stacks.co:20444,02afeae522aab5f8c99a00ddf75fbcb4a641e052dd48836408d9cf437344b63516@seed-1.mainnet.stacks.co:20444,03652212ea76be0ed4cd83a25c06e57819993029a7b9999f7d63c36340b34a4e62@seed-2.mainnet.stacks.co:20444"

[burnchain]
chain = "bitcoin"
mode = "mainnet"
peer_host = "0.0.0.0"
username = "btcuser"
password = "btcpassword"
rpc_port = 19443
peer_port = 19444
```

[logs.log](https://github.com/blockstack/stacks-blockchain/files/7557421/logs.log)
